# Generated by Django 4.2.1 on 2023-08-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
