# Generated by Django 4.2.1 on 2023-08-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_uploaded_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_images',
            name='user_id',
            field=models.EmailField(default='123@nonegmail.com', max_length=100),
        ),
    ]
