# Generated by Django 4.2.1 on 2023-08-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_uploaded_images_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_images',
            name='user_id',
            field=models.EmailField(max_length=100),
        ),
    ]
