# Generated by Django 4.2.1 on 2023-08-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
