# Generated by Django 4.2.1 on 2023-08-24 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_followers_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='is_active',
            new_name='active',
        ),
    ]
