# Generated by Django 4.2.1 on 2023-08-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_is_active_followers_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='active',
            field=models.IntegerField(default=0),
        ),
    ]
