# Generated by Django 4.2.1 on 2023-08-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_followers_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
